# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VIF_ <- function(x, posit_y, posit_x, posit_x_var, correct) {
    .Call(`_miceFast_VIF_`, x, posit_y, posit_x, posit_x_var, correct)
}

fill_NA_N_ <- function(x, model, posit_y, posit_x, w, times = 10L) {
    .Call(`_miceFast_fill_NA_N_`, x, model, posit_y, posit_x, w, times)
}

fill_NA_ <- function(x, model, posit_y, posit_x, w) {
    .Call(`_miceFast_fill_NA_`, x, model, posit_y, posit_x, w)
}

